# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automatic Deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: git config --global user.email "adamhenderson3x3@gmail.com"
      - run: git config --global user.name "evanightly"
      - run: git remote set-url origin https://git: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@github.com/evanightly/evanightly.github.io
      - run: npm run deploy
